name = "TapeMeasure"
uuid = "80345c00-9166-4d3e-8c72-003f651600ad"
authors = ["Cole Miller"]
version = "0.1.0"

[deps]
DispatchDoctor = "8d63f2c5-f18a-4cf2-ba9d-b3f60fc568c8"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extensions]
MakieDimExt = "Makie"
PlotsDimExt = "Plots"

[compat]
DispatchDoctor = "0.4.15"
Makie = "0.21"
Plots = "1.40"
Statistics = "1.10"
Unitful = "1.21"
julia = "1.10"
